# =============================================================================
# Configuration corrigée pour tes 3 serveurs de configuration (configReplSet)
# Alignée sur l'architecture et les volumes de la Personne A.
# =============================================================================
sharding:
  clusterRole: configsvr

replication:
  replSetName: "configReplSet"

net:
  port: 27019
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/mongo-certs/node.pem
    CAFile: /etc/mongo-certs/ca.pem
    allowConnectionsWithoutCertificates: false
    disabledProtocols: "TLS1_0,TLS1_1"

security:
  authorization: enabled
  clusterAuthMode: keyFile
  keyFile: /etc/mongo-keyfile/mongo-cluster.key

storage:
  dbPath: /data/db

systemLog:
  destination: stdout
  logAppend: true
  verbosity: 0

setParameter:
  enableLocalhostAuthBypass: false