# =============================================================================
# Configuration corrigée et harmonisée pour tes 4 Shards de stockage
# Alignée sur l'architecture et le système de débugging de la Personne A.
# =============================================================================
sharding:
  clusterRole: shardsvr

# Note : Le replSetName reste géré dynamiquement par la commande de ton docker-compose.yml

net:
  port: 27018
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/mongo-certs/node.pem
    CAFile: /etc/mongo-certs/ca.pem
    allowConnectionsWithoutCertificates: false
    disabledProtocols: "TLS1_0,TLS1_1"

security:
  authorization: enabled
  clusterAuthMode: keyFile
  keyFile: /etc/mongo-keyfile/mongo-cluster.key

storage:
  dbPath: /data/db

systemLog:
  destination: stdout # CORRIGÉ : Envoie les logs à Docker pour un débugging centralisé et fluide
  logAppend: true
  verbosity: 0

operationProfiling:
  mode: off

setParameter:
  enableLocalhostAuthBypass: false