# =============================================================================
# Configuration corrigée pour les routeurs mongos (Point d'entrée unique)
# Alignée sur la nomenclature et les hostnames de la Personne A.
# =============================================================================
sharding:
  configDB: configReplSet/configServ1:27019,configServ2:27019,configServ3:27019 # CORRIGÉ : pointe vers tes 3 Config Servers réels

net:
  port: 27017
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/mongo-certs/node.pem
    CAFile: /etc/mongo-certs/ca.pem
    allowConnectionsWithoutCertificates: false
    disabledProtocols: "TLS1_0,TLS1_1"

security:
  clusterAuthMode: keyFile
  keyFile: /etc/mongo-keyfile/mongo-cluster.key

systemLog:
  destination: stdout # CORRIGÉ : permet de lire le trafic et de débugger le routeur directement depuis ton terminal Ubuntu
  logAppend: true
  verbosity: 0
